import type { ModelJson } from "../types/ModelJson.type"


export const modelsJsonData: ModelJson[] = [
  {
    "id": "p30v",
    "slug": "p30v",
    "name": "P 30 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q40v,r32v,spv,q80v",
    "related_items": "",
    "short_comment": "Классический вертикальный радиатор с прямоугольным сечением труб 30х60 мм"
  },
  {
    "id": "p30h",
    "slug": "p30h",
    "name": "P 30 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q40h,sph,q80h",
    "related_items": "",
    "short_comment": "Горизонтальная версия популярной модели.  Для установки под  окна"
  },
  {
    "id": "p60v",
    "slug": "p60v",
    "name": "P 60 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "spv,q80v",
    "related_items": "",
    "short_comment": "Плоский дизайн-радиатор с вертикальным расопложением труб. Сечение 30х60 мм"
  },
  {
    "id": "p60h",
    "slug": "p60h",
    "name": "P 60 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "sph,q80h",
    "related_items": "",
    "short_comment": "Горизонтальный радиатор. Плоские трубы, расположенные параллельно стене"
  },
  {
    "id": "sv",
    "slug": "sv",
    "name": "S V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "p30v,spv,rt1v,r32v",
    "related_items": "",
    "short_comment": "Вертикальный радиатор выполнен из стального профиля овальной формы"
  },
  {
    "id": "sh",
    "slug": "sh",
    "name": "S H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "p30h,sph,r32h",
    "related_items": "",
    "short_comment": "Овальное сечение труб 30х50 мм. Горизонтальное расположение"
  },
  {
    "id": "spv",
    "slug": "spv",
    "name": "SP V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "p30v,q40v,r32v",
    "related_items": "",
    "short_comment": "Вертикальный радиатор с секциями овальной формы, расположенными вдоль стены"
  },
  {
    "id": "sph",
    "slug": "sph",
    "name": "SP H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "p30h,q40h,r32h",
    "related_items": "",
    "short_comment": "Горизонтальный радиатор с секциями овальной формы, расположенными вдоль стены"
  },
  {
    "id": "q40v",
    "slug": "q40v",
    "name": "Q 40 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q80v,p30v,qt1v,qt2v",
    "related_items": "",
    "short_comment": "Вертикальный радиатор. Секции имеют квадратное сечение 40х40 мм"
  },
  {
    "id": "q40h",
    "slug": "q40h",
    "name": "Q 40 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q80h,p30h",
    "related_items": "",
    "short_comment": "Горизонтальный радиатор. Секции имеют квадратное сечение 40х40 мм"
  },
  {
    "id": "q60h",
    "slug": "q60h",
    "name": "Q 60 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q40h,q80h,p30h",
    "related_items": "",
    "short_comment": "Горизонтальный радиатор. Секции имеют квадратное сечение 60х60 мм"
  },
  {
    "id": "q60v",
    "slug": "q60v",
    "name": "Q 60 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q40v,q80v,p30v,qt1v,qt2v",
    "related_items": "",
    "short_comment": "Вертикальный радиатор. Секции имеют квадратное сечение 60х60 мм"
  },
  {
    "id": "q80v",
    "slug": "q80v",
    "name": "Q 80 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q40v,p30v,qt1v,qt2v",
    "related_items": "",
    "short_comment": "Вертикальный радиатор. Секции имеют квадратное сечение 80х80 мм"
  },
  {
    "id": "q80h",
    "slug": "q80h",
    "name": "Q 80 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "q40h,p30h",
    "related_items": "",
    "short_comment": "Горизонтальный радиатор. Секции имеют квадратное сечение 80х80 мм"
  },
  {
    "id": "r32v",
    "slug": "r32v",
    "name": "R 32 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "l50,r50,050,lr",
    "related_models": "r89v,rt1v,rt2v,rt1wv",
    "related_items": "",
    "short_comment": "Вертикальная модель. Круглое сечение труб 32 мм"
  },
  {
    "id": "r32h",
    "slug": "r32h",
    "name": "R 32 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat",
    "related_models": "r89h,sph",
    "related_items": "",
    "short_comment": "Горизонтальная модель. Круглое сечение труб 32 мм"
  },
  {
    "id": "r89v",
    "slug": "r89v",
    "name": "R 89 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "l50,r50,050,lr",
    "related_models": "r32v,q80v,rt2v",
    "related_items": "",
    "short_comment": "Вертиальное расположение труб сечением 89 мм"
  },
  {
    "id": "r89h",
    "slug": "r89h",
    "name": "R 89 H",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "horizontal",
    "connections": "lat",
    "related_models": "r32h,q80h",
    "related_items": "",
    "short_comment": "Горизонтальный радиатор с секциями круглой формы 89 мм"
  },
  {
    "id": "rt1v",
    "slug": "rt1v",
    "name": "R T1 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "rt2v,qt1v,rt1wv",
    "related_items": "",
    "short_comment": "Однорядный вертикальный радиатор. Секции круглой формы диаметром 32 мм"
  },
  {
    "id": "rt2v",
    "slug": "rt2v",
    "name": "R T2 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "rt1v,qtv",
    "related_items": "",
    "short_comment": "Двухрядный вертикальный радиатор. Секции круглой формы диаметром 32 мм"
  },
  {
    "id": "rt1wv",
    "slug": "rt1wv",
    "name": "R T1W V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "rt1v,qt1v",
    "related_items": "",
    "short_comment": "Оригинальный вевртикальный радиатор. Диаметр секций 32 мм"
  },
  {
    "id": "qt1v",
    "slug": "qt1v",
    "name": "Q T1 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "qt2v,rt1v,rt1wv",
    "related_items": "",
    "short_comment": "Однорядный вертикальный радиатор. Секции квадратного сечения 40х40 мм"
  },
  {
    "id": "qt2v",
    "slug": "qt2v",
    "name": "Q T2 V",
    "type": "design",
    "prefix": "Дизайн-радиатор",
    "orientation": "vertical",
    "connections": "lat,l50,r50,050,lr",
    "related_models": "qt1v,rt2v",
    "related_items": "",
    "short_comment": "Двухрядный вертикальный радиатор. Секции квадратного сечения 40х40 мм"
  },
  {
    "id": "q500",
    "slug": "q500",
    "name": "Q 500",
    "type": "floor",
    "prefix": "Напольный дизайн-радиатор",
    "orientation": "",
    "connections": "lat,l50,r50,lr",
    "related_models": "p200,p300",
    "related_items": "",
    "short_comment": "Радиатор-скамейка устанавливается в прихожих, гостиных, входных группах и т.д."
  },
  {
    "id": "p200",
    "slug": "p200",
    "name": "P 200",
    "type": "floor",
    "prefix": "Напольный дизайн-радиатор",
    "orientation": "",
    "connections": "lat,l50,r50,lr",
    "related_models": "p300,q500",
    "related_items": "",
    "short_comment": "Напольный радиатор высотой 191 мм. Подходит для установки перед панорамными окнами"
  },
  {
    "id": "p300",
    "slug": "p300",
    "name": "P 300",
    "type": "floor",
    "prefix": "Напольный дизайн-радиатор",
    "orientation": "",
    "connections": "lat,l50,r50,lr",
    "related_models": "p200,q500",
    "related_items": "",
    "short_comment": "Напольный радиатор высотой 191 мм. Подходит для установки перед панорамными окнами"
  },
  {
    "id": "kwh",
    "slug": "kwh",
    "name": "KWH",
    "type": "convector",
    "prefix": "Внутрипольный конвектор",
    "orientation": "",
    "connections": "",
    "related_models": "kwhv",
    "related_items": "",
    "short_comment": "Естественная конвекция. Ширина 150-420 мм. Высота 65-140 мм"
  },
  {
    "id": "kwhv",
    "slug": "kwhv",
    "name": "KWHV",
    "type": "convector",
    "prefix": "Внутрипольный конвектор",
    "orientation": "",
    "connections": "",
    "related_models": "kwh",
    "related_items": "",
    "short_comment": "Принудительная конвекция. Ширина 250-420 мм. Высота 85-140 мм"
  },
  {
    "id": "nostalgia500",
    "slug": "nostalgia500",
    "name": "Nostalgia 500",
    "type": "ironcast",
    "prefix": "Чугунный ретро-радиатор",
    "orientation": "",
    "connections": "",
    "related_models": "historic500",
    "related_items": "",
    "short_comment": "Чугунный ретро-радиатор в стиле ретро. Украшен цветочным орнаментом"
  },
  {
    "id": "historic500",
    "slug": "historic500",
    "name": "Historic 500",
    "type": "ironcast",
    "prefix": "Чугунный ретро-радиатор",
    "orientation": "",
    "connections": "",
    "related_models": "nostalgia500",
    "related_items": "",
    "short_comment": "Чугунный радиатор без орнамента. Отлично подходит для интерьеров в стиле лофт"
  }
]
