import type { ModelJson } from '../types/ModelJson.type'

export const modelsJsonData: ModelJson[] = [
	{
		id: 'r42v',
		slug: 'r42v',
		name: 'R 42 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'l50,r50,050,lr',
		related_models: 'r89v,rt1v,rt2v,rt1wv,r32v',
		related_items: '',
		short_comment: 'Вертикальная модель. Круглое сечение труб 42 мм',
	},
	{
		id: 'r42h',
		slug: 'r42h',
		name: 'R 42 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'r89h,sph,r42h',
		related_items: '',
		short_comment: 'Горизонтальная модель. Круглое сечение труб 42 мм',
	},
	{
		id: 'p30v',
		slug: 'p30v',
		name: 'P 30 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q40v,r32v,spv,q80v',
		related_items: '',
		short_comment: 'Классический вертикальный радиатор с прямоугольным сечением труб 30х60 мм.',
	},
	{
		id: 'p30h',
		slug: 'p30h',
		name: 'P 30 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q40h,sph,q80h',
		related_items: '',
		short_comment: 'Горизонтальная версия популярной модели.  Для установки под  окна.',
	},
	{
		id: 'p60v',
		slug: 'p60v',
		name: 'P 60 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'spv,q80v',
		related_items: '',
		short_comment: 'Плоский дизайн-радиатор с вертикальным расопложением труб. Сечение 30х60 мм.',
	},
	{
		id: 'p60h',
		slug: 'p60h',
		name: 'P 60 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'sph,q80h',
		related_items: '',
		short_comment: 'Горизонтальный радиатор. Плоские трубы, расположенные параллельно стене.',
	},
	{
		id: 'sv',
		slug: 'sv',
		name: 'S V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'p30v,spv,rt1v,r32v',
		related_items: '',
		short_comment: 'Вертикальный радиатор выполнен из стального профиля овальной формы.',
	},
	{
		id: 'sh',
		slug: 'sh',
		name: 'S H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'p30h,sph,r32h',
		related_items: '',
		short_comment: 'Овальное сечение труб 30х50 мм. Горизонтальное расположение.',
	},
	{
		id: 'spv',
		slug: 'spv',
		name: 'SP V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'p30v,q40v,r32v',
		related_items: '',
		short_comment: 'Вертикальный радиатор с секциями овальной формы, расположенными вдоль стены.',
	},
	{
		id: 'sph',
		slug: 'sph',
		name: 'SP H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'p30h,q40h,r32h',
		related_items: '',
		short_comment: 'Горизонтальный радиатор с секциями овальной формы, расположенными вдоль стены.',
	},
	{
		id: 'q40v',
		slug: 'q40v',
		name: 'Q 40 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q80v,p30v,qt1v,qt2v',
		related_items: '',
		short_comment: 'Вертикальный радиатор. Секции имеют квадратное сечение 40х40 мм.',
	},
	{
		id: 'q40h',
		slug: 'q40h',
		name: 'Q 40 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q80h,p30h',
		related_items: '',
		short_comment: 'Горизонтальный радиатор. Секции имеют квадратное сечение 40х40 мм.',
	},
	{
		id: 'q60v',
		slug: 'q60v',
		name: 'Q 60 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q40v,p80v,qt1v,qt2v',
		related_items: '',
		short_comment: 'Вертикальный радиатор. Секции имеют квадратное сечение 60х60 мм.',
	},
	{
		id: 'q60h',
		slug: 'q60h',
		name: 'Q 60 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q40h,q80h,p30h',
		related_items: '',
		short_comment: 'Горизонтальный радиатор. Секции имеют квадратное сечение 60х60 мм.',
	},
	{
		id: 'q80v',
		slug: 'q80v',
		name: 'Q 80 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q40v,p30v,q60v,qt1v,qt2v',
		related_items: '',
		short_comment: 'Вертикальный радиатор. Секции имеют квадратное сечение 80х80 мм.',
	},
	{
		id: 'q80h',
		slug: 'q80h',
		name: 'Q 80 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'q40h,q60h,p30h',
		related_items: '',
		short_comment: 'Горизонтальный радиатор. Секции имеют квадратное сечение 80х80 мм.',
	},
	{
		id: 'r32v',
		slug: 'r32v',
		name: 'R 32 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'l50,r50,050,lr',
		related_models: 'r89v,rt1v,rt2v,rt1wv,r42v',
		related_items: '',
		short_comment: 'Вертикальная модель. Круглое сечение труб 32 мм',
	},
	{
		id: 'r32h',
		slug: 'r32h',
		name: 'R 32 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat',
		related_models: 'r89h,sph,r42h',
		related_items: '',
		short_comment: 'Горизонтальная модель. Круглое сечение труб 32 мм',
	},
	{
		id: 'r42v',
		slug: 'r42v',
		name: 'R 42 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'l50,r50,050,lr',
		related_models: 'r89v,rt1v,rt2v,rt1wv,r32v',
		related_items: '',
		short_comment: 'Вертикальная модель. Круглое сечение труб 42 мм',
	},
	{
		id: 'r42h',
		slug: 'r42h',
		name: 'R 42 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'r89h,sph,r42h',
		related_items: '',
		short_comment: 'Горизонтальная модель. Круглое сечение труб 42 мм',
	},
	{
		id: 'r89v',
		slug: 'r89v',
		name: 'R 89 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'l50,r50,050,lr',
		related_models: 'r32v,q80v,rt2v',
		related_items: '',
		short_comment: 'Вертиальное расположение труб сечением 89 мм',
	},
	{
		id: 'r89h',
		slug: 'r89h',
		name: 'R 89 H',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'horizontal',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'r32h,q80h',
		related_items: '',
		short_comment: 'Горизонтальный радиатор с секциями круглой формы 89 мм',
	},
	{
		id: 'rt1v',
		slug: 'rt1v',
		name: 'R T1 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'rt2v,qt1v,rt1wv',
		related_items: '',
		short_comment: 'Однорядный вертикальный радиатор. Секции круглой формы диаметром 32 мм',
	},
	{
		id: 'rt2v',
		slug: 'rt2v',
		name: 'R T2 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'rt1v,qtv',
		related_items: '',
		short_comment: 'Двухрядный вертикальный радиатор. Секции круглой формы диаметром 32 мм',
	},
	{
		id: 'rt1wv',
		slug: 'rt1wv',
		name: 'R T1W V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'rt1v,qt1v',
		related_items: '',
		short_comment: 'Оригинальный вевртикальный радиатор. Диаметр секций 32 мм.',
	},
	{
		id: 'qt1v',
		slug: 'qt1v',
		name: 'Q T1 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'qt2v,rt1v,rt1wv',
		related_items: '',
		short_comment: 'Однорядный вертикальный радиатор. Секции квадратного сечения 40х40 мм',
	},
	{
		id: 'qt2v',
		slug: 'qt2v',
		name: 'Q T2 V',
		type: 'design',
		prefix: 'Дизайн-радиатор',
		orientation: 'vertical',
		connections: 'lat,l50,r50,050,lr',
		related_models: 'qt1v,rt2v',
		related_items: '',
		short_comment: 'Двухрядный вертикальный радиатор. Секции квадратного сечения 40х40 мм',
	},
	{
		id: 'q500',
		slug: 'q500',
		name: 'Q 500',
		type: 'floor',
		prefix: 'Напольный дизайн-радиатор',
		orientation: '',
		connections: 'lat,l50,r50,lr',
		related_models: 'p200,p300',
		related_items: '',
		short_comment: 'Радиатор-скамейка устанавливается в прихожих, гостиных, входных группах и т.д.',
	},
	{
		id: 'p200',
		slug: 'p200',
		name: 'P 200',
		type: 'floor',
		prefix: 'Напольный дизайн-радиатор',
		orientation: '',
		connections: 'lat,l50,r50,lr',
		related_models: 'p300,q500',
		related_items: '',
		short_comment: 'Напольный радиатор высотой 191 мм. Подходит для установки перед панорамными окнами.',
	},
	{
		id: 'p300',
		slug: 'p300',
		name: 'P 300',
		type: 'floor',
		prefix: 'Напольный дизайн-радиатор',
		orientation: '',
		connections: 'lat,l50,r50,lr',
		related_models: 'p200,q500',
		related_items: '',
		short_comment: 'Напольный радиатор высотой 191 мм. Подходит для установки перед панорамными окнами.',
	},
	{
		id: 'kwh',
		slug: 'kwh',
		name: 'KWH',
		type: 'convector',
		prefix: 'Внутрипольный конвектор',
		orientation: '',
		connections: '',
		related_models: 'kwhv',
		related_items: '',
		short_comment: 'Естественная конвекция. Ширина 150-420 мм. Высота 65-140 мм.',
	},
	{
		id: 'kwhv',
		slug: 'kwhv',
		name: 'KWHV',
		type: 'convector',
		prefix: 'Внутрипольный конвектор',
		orientation: '',
		connections: '',
		related_models: 'kwh',
		related_items: '',
		short_comment: 'Принудительная конвекция. Ширина 250-420 мм. Высота 85-140 мм.',
	},
	{
		id: 'kwhv24',
		slug: 'kwhv24',
		name: 'KWHV 24V',
		type: 'convector',
		prefix: 'Внутрипольный конвектор',
		orientation: '',
		connections: '',
		related_models: 'kwhv',
		related_items: '',
		short_comment: 'Принудительная конвекция. Вентиляторы 24В. Ширина 200-420 мм. Высота 85-140 мм.',
	},
	{
		id: 'nostalgia500',
		slug: 'nostalgia500',
		name: 'Nostalgia 500',
		type: 'ironcast',
		prefix: 'Чугунный ретро-радиатор',
		orientation: '',
		connections: '',
		related_models: 'historic500,nostalgia300',
		related_items: '',
		short_comment: 'Чугунный ретро-радиатор в стиле ретро. Украшен цветочным орнаментом',
	},
	{
		id: 'historic500',
		slug: 'historic500',
		name: 'Historic 500',
		type: 'ironcast',
		prefix: 'Чугунный ретро-радиатор',
		orientation: '',
		connections: '',
		related_models: 'nostalgia500,historic300',
		related_items: '',
		short_comment: 'Чугунный радиатор без орнамента. Отлично подходит для интерьеров в стиле лофт',
	},
	{
		id: 'nostalgia300',
		slug: 'nostalgia300',
		name: 'Nostalgia 300',
		type: 'ironcast',
		prefix: 'Чугунный ретро-радиатор',
		orientation: '',
		connections: '',
		related_models: 'historic300,nostalgia300',
		related_items: '',
		short_comment: 'Чугунный ретро-радиатор в стиле ретро. Украшен цветочным орнаментом',
	},
	{
		id: 'historic300',
		slug: 'historic300',
		name: 'Historic 300',
		type: 'ironcast',
		prefix: 'Чугунный ретро-радиатор',
		orientation: '',
		connections: '',
		related_models: 'nostalgia300,historic500',
		related_items: '',
		short_comment: 'Чугунный радиатор без орнамента. Отлично подходит для интерьеров в стиле лофт',
	},
	{
		id: '3020',
		slug: '3020',
		name: '3020',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2030,4030',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 190 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 28.7 Вт.',
	},
	{
		id: '2030',
		slug: '2030',
		name: '2030',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3030,4030,2037,3037',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 300 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 34.7 Вт.',
	},
	{
		id: '3030',
		slug: '3030',
		name: '3030',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2030,4030,3037',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 300 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 41.1 Вт.',
	},
	{
		id: '4030',
		slug: '4030',
		name: '4030',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2030,3030,4037',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 300 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 53.7 Вт.',
	},
	{
		id: '2037',
		slug: '2037',
		name: '2037',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3037,4037,2030,2040',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 376 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 42.5 Вт.',
	},
	{
		id: '3037',
		slug: '3037',
		name: '3037',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2037,4037,3030,3040',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 376 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 49.5 Вт.',
	},
	{
		id: '4037',
		slug: '4037',
		name: '4037',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2037,3037,4030,4040',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 376 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 65.8 Вт.',
	},
	{
		id: '2040',
		slug: '2040',
		name: '2040',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3040,4040,2037,2045',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 400 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 45.8 Вт.',
	},
	{
		id: '3040',
		slug: '3040',
		name: '3040',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2040,4040,3037,3045',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 400 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 53.7 Вт.',
	},
	{
		id: '4040',
		slug: '4040',
		name: '4040',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2040,3040,4037,4045',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 400 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 70.4 Вт.',
	},
	{
		id: '2045',
		slug: '2045',
		name: '2045',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3045,4045,2040,2050',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 450 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 51 Вт.',
	},
	{
		id: '3045',
		slug: '3045',
		name: '3045',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2045,4045,3040,3050',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 450 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 59.9 Вт.',
	},
	{
		id: '4045',
		slug: '4045',
		name: '4045',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2045,3045,4040,4050',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 450 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 78.5 Вт.',
	},
	{
		id: '2050',
		slug: '2050',
		name: '2050',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3050,4050,2045,2057',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 500 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 56.5 Вт.',
	},
	{
		id: '3050',
		slug: '3050',
		name: '3050',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2050,4050,3045,3057',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 500 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 66 Вт.',
	},
	{
		id: '4050',
		slug: '4050',
		name: '4050',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2050,3050,4055,4057',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 500 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 86.5 Вт.',
	},
	{
		id: '2055',
		slug: '2055',
		name: '2055',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3055,4055,2050,2057',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 550 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 61.3 Вт.',
	},
	{
		id: '3055',
		slug: '3055',
		name: '3055',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2055,4055,3050,3057',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 550 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 72 Вт.',
	},
	{
		id: '4055',
		slug: '4055',
		name: '4055',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2055,3055,4050,4057',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 550 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 94.3 Вт.',
	},
	{
		id: '2057',
		slug: '2057',
		name: '2057',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3057,4057,2055,2060',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 576 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 62.7 Вт.',
	},
	{
		id: '3057',
		slug: '3057',
		name: '3057',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2057,4057,3055,3060',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 576 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 73.9 Вт.',
	},
	{
		id: '4057',
		slug: '4057',
		name: '4057',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2057,3057,4050,4060',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 576 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 97.3 Вт.',
	},
	{
		id: '2060',
		slug: '2060',
		name: '2060',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3060,4060,2057,2075',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 600 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 66.1 Вт.',
	},
	{
		id: '3060',
		slug: '3060',
		name: '3060',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2060,4060,3057,3075',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 600 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 77.9 Вт.',
	},
	{
		id: '4060',
		slug: '4060',
		name: '4060',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2060,3060,4057,4075',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 600 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 101.9 Вт.',
	},
	{
		id: '2075',
		slug: '2075',
		name: '2075',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3075,4075,2060,2090',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 750 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 80 Вт.',
	},
	{
		id: '3075',
		slug: '3075',
		name: '3075',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2075,4075,3060,3090',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 750 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 94.8 Вт.',
	},
	{
		id: '4075',
		slug: '4075',
		name: '4075',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2075,3075,4060,4090',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 750 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 122.9 Вт.',
	},
	{
		id: '2090',
		slug: '2090',
		name: '2090',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3090,4090,2075,2100',
		related_items: '',
		short_comment: 'Двух-трубчатый радиатор высотой 900 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 92.7 Вт.',
	},
	{
		id: '3090',
		slug: '3090',
		name: '3090',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2090,4090,3075,3100',
		related_items: '',
		short_comment: 'Трех-трубчатый радиатор высотой 900 мм. Число секций от 4 до 50. Мощность секции (ΔT60): 110.8 Вт.',
	},
	{
		id: '4090',
		slug: '4090',
		name: '4090',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2090,3090,4075,4100',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 900 мм. Число секций от 4 до 46. Мощность секции (ΔT60): 142.8 Вт.',
	},
	{
		id: '2100',
		slug: '2100',
		name: '2100',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3100,4100,2090,2110',
		related_items: '',
		short_comment:
			'Двух-трубчатый радиатор высотой 1000 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 100.5 Вт.',
	},
	{
		id: '3100',
		slug: '3100',
		name: '3100',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2100,4100,3090,3110',
		related_items: '',
		short_comment:
			'Трех-трубчатый радиатор высотой 1000 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 120.9 Вт.',
	},
	{
		id: '4100',
		slug: '4100',
		name: '4100',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2100,3100,4090,4110',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 1000 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 154.9 Вт.',
	},
	{
		id: '2110',
		slug: '2110',
		name: '2110',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3110,4110,2100,2120',
		related_items: '',
		short_comment:
			'Двух-трубчатый радиатор высотой 1100 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 107.8 Вт.',
	},
	{
		id: '3110',
		slug: '3110',
		name: '3110',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2110,4110,3100,3120',
		related_items: '',
		short_comment:
			'Трех-трубчатый радиатор высотой 1100 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 130.6 Вт.',
	},
	{
		id: '4110',
		slug: '4110',
		name: '4110',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2110,3110,4100,4120',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 1100 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 165.6 Вт.',
	},
	{
		id: '2120',
		slug: '2120',
		name: '2120',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3120,4120,2110,2150',
		related_items: '',
		short_comment:
			'Двух-трубчатый радиатор высотой 1200 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 122.9 Вт.',
	},
	{
		id: '3120',
		slug: '3120',
		name: '3120',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2120,4120,3110,3150',
		related_items: '',
		short_comment:
			'Трех-трубчатый радиатор высотой 1200 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 148.7 Вт.',
	},
	{
		id: '4120',
		slug: '4120',
		name: '4120',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2120,3120,4110,4150',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 1200 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 189.1 Вт.',
	},
	{
		id: '2150',
		slug: '2150',
		name: '2150',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3150,4150,2120,2180',
		related_items: '',
		short_comment:
			'Двух-трубчатый радиатор высотой 1500 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 153.9 Вт.',
	},
	{
		id: '3150',
		slug: '3150',
		name: '3150',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2150,4150,3120,3180',
		related_items: '',
		short_comment:
			'Трех-трубчатый радиатор высотой 1500 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 181.9 Вт.',
	},
	{
		id: '4150',
		slug: '4150',
		name: '4150',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2150,3150,4120,4180',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 1500 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 233.5 Вт.',
	},
	{
		id: '2180',
		slug: '2180',
		name: '2180',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3180,4180,2150,2200',
		related_items: '',
		short_comment:
			'Двух-трубчатый радиатор высотой 1800 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 184.1 Вт.',
	},
	{
		id: '3180',
		slug: '3180',
		name: '3180',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2180,4180,3150,3200',
		related_items: '',
		short_comment:
			'Трех-трубчатый радиатор высотой 1800 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 215.1 Вт.',
	},
	{
		id: '4180',
		slug: '4180',
		name: '4180',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2180,3180,4150,4200',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 1800 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 276.2 Вт.',
	},
	{
		id: '2200',
		slug: '2200',
		name: '2200',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '3200,4200,2180',
		related_items: '',
		short_comment:
			'Двух-трубчатый радиатор высотой 2000 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 203.8 Вт.',
	},
	{
		id: '3200',
		slug: '3200',
		name: '3200',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2200,4200,3180',
		related_items: '',
		short_comment:
			'Трех-трубчатый радиатор высотой 2000 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 237.3 Вт.',
	},
	{
		id: '4200',
		slug: '4200',
		name: '4200',
		type: 'columns',
		prefix: 'Трубчатый радиатор',
		orientation: '',
		connections: '',
		related_models: '2200,3200,4180',
		related_items: '',
		short_comment:
			'Четырех-трубчатый радиатор высотой 2000 мм. Число секций от 4 до 20. Мощность секции (ΔT60): 304.7 Вт.',
	},
]
